const $=s=>document.querySelector(s);let stream=null,screenStream=null,recorder=null,chunks=[],micOn=true,camOn=true,seconds=0,peer=null,dataChannel=null,isCaller=false;const rtcConfig={iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'}]};const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)};function updateTimer(){seconds++;$('#meetingTimer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}setInterval(updateTimer,1000);
async function initMedia(){if(stream){$('#localVideo').srcObject=stream;return true}try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('media-unavailable');stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});$('#localVideo').srcObject=stream;$('#localPlaceholder').style.display='none';toast('تم تشغيل الكاميرا والميكروفون');return true}catch(e){toast('اسمح بالوصول للكاميرا والميكروفون من HTTPS أو localhost');return false}}
function waitForIce(){return new Promise(resolve=>{if(!peer||peer.iceGatheringState==='complete')return resolve();const done=()=>{if(peer.iceGatheringState==='complete'){peer.removeEventListener('icegatheringstatechange',done);resolve()}};peer.addEventListener('icegatheringstatechange',done);setTimeout(resolve,8000)})}
function signalEncode(value){return btoa(unescape(encodeURIComponent(JSON.stringify(value))))}
function signalDecode(value){try{return JSON.parse(decodeURIComponent(escape(atob(value.trim()))))}catch(e){toast('رمز الاتصال غير صحيح');return null}}
function updateParticipants(connected){const count=connected?2:1;$('#participantCount').textContent=count;$('#participantLabel').textContent=`${count} مشارك${count===1?'':'ين'}`;$('#remoteCard').style.display=connected?'flex':'none';if(connected){$('#remotePeople').innerHTML='<div class="person" id="remotePerson"><span class="person-avatar green">م</span><div><b>المشارك المتصل</b><small>متصل الآن</small></div><span id="remotePersonMic">🎙</span></div>'}else $('#remotePeople').innerHTML=''}
function setupPeer(){peer=new RTCPeerConnection(rtcConfig);updateParticipants(false);stream?.getTracks().forEach(track=>peer.addTrack(track,stream));peer.ontrack=e=>{$('#remoteVideo').srcObject=e.streams[0];$('#remotePlaceholder').style.display='none';$('#remoteStatus').textContent='متصل';updateParticipants(true)};peer.onconnectionstatechange=()=>{$('#p2pStatus').textContent=`الحالة: ${peer.connectionState}`;if(peer.connectionState==='connected'){updateParticipants(true);toast('تم الاتصال المباشر بنجاح')}if(['failed','disconnected','closed'].includes(peer.connectionState)){updateParticipants(false);$('#remoteStatus').textContent='في انتظار الاتصال';$('#remotePlaceholder').style.display='flex';toast('انقطع اتصال المشارك')}};peer.ondatachannel=e=>{dataChannel=e.channel;setupDataChannel()}}
function setupDataChannel(){if(!dataChannel)return;dataChannel.onopen=()=>toast('قناة المحادثة متصلة');dataChannel.onmessage=e=>{try{const p=JSON.parse(e.data);if(p.type==='chat'){const item=document.createElement('div');item.className='chat-item';item.textContent=p.text;$('#chatList').append(item)}if(p.type==='reaction')toast(`تفاعل المشارك ${p.text}`)}catch(_){}}}
async function createConnection(kind){if(!(await initMedia()))return;if(peer){peer.close();peer=null;dataChannel=null}setupPeer();if(kind==='offer'){isCaller=true;dataChannel=peer.createDataChannel('meet-chat');setupDataChannel();await peer.setLocalDescription(await peer.createOffer())}else{isCaller=false;$('#p2pStatus').textContent='ألصق عرض المضيف أولاً ثم اضغط معالجة الرمز';return}await waitForIce();$('#signalOutput').value=signalEncode(peer.localDescription);$('#p2pStatus').textContent='انسخ العرض وأرسله للمشارك'}
function toggleTrack(kind){if(!stream)return;const tracks=kind==='audio'?stream.getAudioTracks():stream.getVideoTracks();const on=tracks.some(t=>t.enabled);tracks.forEach(t=>t.enabled=!on);const btn=kind==='audio'?$('#micBtn'):$('#cameraBtn');btn.classList.toggle('off',on);if(kind==='audio'){$('#localMicState').textContent=on?'🔇':'🎙';micOn=!on}else{camOn=!on;$('#localPlaceholder').style.display=on?'flex':'none'}toast(on?(kind==='audio'?'تم كتم الميكروفون':'تم إيقاف الكاميرا'):'تم التشغيل')}
$('#micBtn').onclick=()=>toggleTrack('audio');$('#cameraBtn').onclick=()=>toggleTrack('video');
$('#shareBtn').onclick=async()=>{try{if(screenStream){screenStream.getTracks().forEach(t=>t.stop());screenStream=null;$('#localVideo').srcObject=stream;$('#shareBtn').classList.remove('active');return}screenStream=await navigator.mediaDevices.getDisplayMedia({video:true});$('#localVideo').srcObject=screenStream;$('#shareBtn').classList.add('active');screenStream.getVideoTracks()[0].onended=()=>{$('#shareBtn').click()};toast('بدأت مشاركة الشاشة')}catch(e){toast('لم تبدأ مشاركة الشاشة')}};
$('#chatBtn').onclick=()=>{$('#sidePanel').classList.add('open');document.querySelector('[data-panel="chatPanel"]').click()};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab,.panel-content').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.panel).classList.add('active');$('#sidePanel').classList.add('open')});
$('#chatForm').onsubmit=e=>{e.preventDefault();const input=$('#chatInput'),text=input.value.trim();if(!text)return;const item=document.createElement('div');item.className='chat-item me';item.textContent=text;$('#chatList').append(item);if(dataChannel?.readyState==='open')dataChannel.send(JSON.stringify({type:'chat',text}));input.value='';$('#messageCount').textContent=+$('#messageCount').textContent+1;$('#chatList').scrollTop=1e6};
$('#connectBtn').onclick=()=>$('#connectDialog').showModal();$('#connectClose').onclick=()=>$('#connectDialog').close();$('#createOfferBtn').onclick=()=>createConnection('offer');$('#createAnswerBtn').onclick=()=>createConnection('answer');$('#applySignalBtn').onclick=async()=>{const value=signalDecode($('#signalInput').value);if(!value)return;if(!(await initMedia()))return;if(!peer){setupPeer()}try{await peer.setRemoteDescription(value);if(value.type==='offer'){await peer.setLocalDescription(await peer.createAnswer());await waitForIce();$('#signalOutput').value=signalEncode(peer.localDescription);$('#p2pStatus').textContent='انسخ الرد وأرسله إلى المضيف'}else{$('#p2pStatus').textContent='تمت معالجة الرد، انتظر الاتصال'}toast('تمت معالجة رمز الاتصال')}catch(e){$('#p2pStatus').textContent='تعذر معالجة الرمز';toast('رمز الاتصال غير صالح أو مستخدم سابقاً')}};$('#copySignalBtn').onclick=async()=>{const value=$('#signalOutput').value.trim();if(!value){toast('أنشئ رمز الاتصال أولاً');return}try{await navigator.clipboard.writeText(value);toast('تم نسخ رمز الاتصال')}catch(e){$('#signalOutput').select();toast('انسخ الرمز المحدد يدوياً')}};
$('#reactionBtn').onclick=()=>$('#reactionMenu').classList.toggle('show');document.querySelectorAll('#reactionMenu button').forEach(b=>b.onclick=()=>{const text=b.textContent;toast(`أرسلت تفاعلاً ${text}`);if(dataChannel?.readyState==='open')dataChannel.send(JSON.stringify({type:'reaction',text}));$('#reactionMenu').classList.remove('show')});
$('#boardBtn').onclick=()=>{$('#whiteboard').classList.toggle('show');$('#videoGrid').style.display=$('#whiteboard').classList.contains('show')?'none':'grid';if($('#whiteboard').classList.contains('show'))resizeBoard()};const canvas=$('#boardCanvas'),ctx=canvas.getContext('2d');let drawing=false;function resizeBoard(){canvas.width=canvas.clientWidth;canvas.height=canvas.clientHeight}window.addEventListener('resize',resizeBoard);canvas.onpointerdown=e=>{drawing=true;ctx.beginPath();ctx.moveTo(e.offsetX,e.offsetY)};canvas.onpointerup=()=>drawing=false;canvas.onpointermove=e=>{if(!drawing)return;ctx.strokeStyle=$('#boardColor').value;ctx.lineWidth=4;ctx.lineCap='round';ctx.lineTo(e.offsetX,e.offsetY);ctx.stroke()};$('#clearBoard').onclick=()=>ctx.clearRect(0,0,canvas.width,canvas.height);
$('#recordBtn').onclick=()=>{if(!stream){toast('شغّل الكاميرا أولاً');return}if(!recorder){chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(chunks,{type:'video/webm'}));a.download=`netgits-meet-${Date.now()}.webm`;a.click();recorder=null};recorder.start();$('#recordBtn').classList.add('active');toast('بدأ التسجيل محلياً')}else{recorder.stop();$('#recordBtn').classList.remove('active');toast('تم حفظ التسجيل')}};
$('#copyBtn').onclick=async()=>{$('#connectDialog').showModal();toast('استخدم اتصال P2P لإنشاء عرض وإرساله للطرف الآخر')};$('#inviteBtn').onclick=()=>$('#connectBtn').click();$('#addParticipant').onclick=()=>$('#connectBtn').click();$('#statsBtn').onclick=()=>$('#statsDialog').showModal();$('.dialog-close').onclick=()=>$('#statsDialog').close();$('#fullscreenBtn').onclick=()=>document.documentElement.requestFullscreen?.();$('#layoutBtn').onclick=()=>{$('#videoGrid').classList.toggle('single');toast('تم تبديل التخطيط')};$('#leaveBtn').onclick=()=>{stream?.getTracks().forEach(t=>t.stop());screenStream?.getTracks().forEach(t=>t.stop());toast('تم إنهاء الاجتماع');setTimeout(()=>location.reload(),700)};initMedia();
